AWSTemplateFormatVersion: 2010-09-09
Description: >
  Sample template for deploying an Amazon Kinesis Data Stream
  with a role that another account can assume to 
  write to the stream. Optionally add encryption by specifying
  an AWS Key Management System encryption key.

Parameters:
  BrightspaceAccountId:
    Type: String
    Description: >
      The identifier of the account that will
      publish messages *to* the Amazon Kinesis Data Stream
  RetentionPeriodHours:
    Type: Number
    Default: 24
    Description: >
      The number of hours for the data records that are stored in shards to 
      remain accessible. The default value is 24. For more information 
      about the stream retention period, see Changing the Data Retention 
      Period in the Amazon Kinesis Developer Guide.
      See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html
  ShardCount:
    Type: Number
    Default: 1
    Description: >
      The number of shards that the stream uses. For greater provisioned throughput, increase the number of shards.
      See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html
  StreamEncryptionKeyId:
    Type: String
    Default: ""
    Description: >
      The GUID for the customer-managed AWS KMS key to use for encryption.
      This value must be exactly the Guid, in order for Brightspace to write to the shard. 
      See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html

Conditions:
  HasEncryption: !Not [!Equals ["", !Ref StreamEncryptionKeyId]]

Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      RetentionPeriodHours: !Ref RetentionPeriodHours
      ShardCount: !Ref ShardCount
      StreamEncryption: 
        !If 
          - HasEncryption
          - { EncryptionType: "KMS",
              KeyId: !Ref StreamEncryptionKeyId }
          - !Ref "AWS::NoValue"
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref BrightspaceAccountId
          Action: "sts:AssumeRole"
      Policies:
        - PolicyName: streamWriterPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Resource: !GetAtt KinesisStream.Arn
              Action:
              - "kinesis:PutRecord"
              - "kinesis:PutRecords"
        - !If
            - HasEncryption
            - PolicyName: encryptionPolicy
              PolicyDocument:
                Version: 2012-10-17
                Statement:
                - Effect: Allow
                  Action: "kms:GenerateDataKey"
                  Resource: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${StreamEncryptionKeyId}"
            - !Ref "AWS::NoValue"

Outputs:
  IamRoleArn:
    Description: >
      The ARN of the Amazon IAM Role that the lambda will assume
      to write events to a customer Amazon Kinesis Data Stream.
    Value: !GetAtt IamRole.Arn
  KinesisStreamName:
    Description: >
      The identifier of the Amazon Kinesis Data Stream that Brightspace
      events will be written to.
    Value: !Ref KinesisStream